name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  pr_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Description cannot be empty
        uses: actions-ecosystem/action-regex-match@v2
        with:
          text: ${{github.event.pull_request.body}}
          regex: '^$|\s+'
          flags: gm
